###login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "test_username2",
  "password": "testpassword2"
}

###delete a blog
DELETE http://localhost:3001/api/blogs/669c286826eb51958f925302
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNlcm5hbWUyIiwiaWQiOiI2NjljMTk5MTFiYjljNjBlMjY2OGYwM2QiLCJpYXQiOjE3MjE1MTAxNjV9.ALm021fKdpfGkf_vT2mcEXFJ7W_2cIFSDqO6NmgaPN0
Content-Type: application/json
